### ISSUE TITLE
Adding Skills

### ISSUE THREAD

**Issue by EclipsePhaseGM** [DerDiemen/eclipsephase#17]
First off let me thank you for your work on this. I have been using roll20 to run Eclipse Phase and it was... inadequate.

I've run into an issue with player character creation: the "add first exotic skill" and "add first know skill" buttons do not function. I understand this is a hobby project of yours and I apologize for bothering you. If you could just check this issue out I would appreciate it greatly.

**Comment by DerDiemen** [comment]
Hey EclispePhaseGM,

thanks for the nice words, I hope that my system fits your needs a bit better, as Foundry fits everyones needs better than R20 ;) 

As for the bug: Good catch! I didn't notice, but I'll have a look into it to try to fix it today.

All the best

Diemen

**Comment by DerDiemen** [comment]
I found a work-around-solution which (hopefully) doesn't break anything else. I'll push the same after testing it a bit later today. Thanks again for raising this issue!

**Comment by EclipsePhaseGM** [comment]
It appears to have been resolved. I can add skills for the players now. Thank you so much.

**Comment by DerDiemen** [comment]
Aaah! You're using the master branch, yes? - That would at least explain why you already have the changes :) 

Please note that my master branch maybe broken sometimes, since I'm using this to test new features in my own games. If this is okay with you feel free to use it. Otherwise I would recommend on waiting for the release and download this directly through the repository.

Glad I could fix the problem for now.

**Comment by EclipsePhaseGM** [comment]
> Aaah! You're using the master branch, yes? - That would at least explain why you already have the changes :)
> 
> Please note that my master branch maybe broken sometimes, since I'm using this to test new features in my own games. If this is okay with you feel free to use it. Otherwise I would recommend on waiting for the release and download this directly through the repository.

Word. The players and I have noticed a few issues and I've tried to keep track of them. If you'll appreciate the help testing your system, I'll be glad to keep you informed of what we encounter. It's up to you regardless; I don't want to inundate you with unwanted notes.

**Comment by DerDiemen** [comment]
Sure, keep them coming. I'll see what I can do you fix them :)
