### ISSUE TITLE
mostly minor issues besides the threat roll problem

### ISSUE THREAD

**Issue by EclipsePhaseGM** [DerDiemen/eclipsephase#18]
Ego Traits:
-Composure listed as negative trait
-Obtuseness listed as positive trait

Threat-type Actors:
-All attack rolls become melee attacks. The prompt for roll modifiers for melee attacks comes up regardless of what attack type it is.

Skills:
-Knowledge skill specializations rolling as “skill value lower than zero”
-Deceive skill is linked to Somatics rather than Savvy.

**Comment by DerDiemen** [comment]
Hey hey,

Great! Thank you for adding this list. It really helps me keeping track of bugs, since I‘m my only tester so far ;) 

I‘ll work them out and push an update once done. I hope this will be somewhere start of next week!

**Comment by DerDiemen** [comment]
All issues have been accounted for and been fixed! You'll find the fixes in the latest release! Thanks for your help in making this a better system :)
