### ISSUE TITLE
Please Add Smart Creatures in the packs.

### ISSUE THREAD

**Issue by herrozerro** [DerDiemen/eclipsephase#31]
Smart creatures are a large section of the rules that are not in the compendium packs.

**Comment by DerDiemen** [comment]
So after analyzing smart animals I came to the conclusion, that they are FAR more difficult to implement than any other items.

That said, they'll come to the sheet with the next update in a very chaotic and not very functional way, but at least they will be there and in their compendium. I'll then will update the whole thing while updating the old vehicles tab (now called peripherals) somwhere during 0.8.x while my main focus will stay on making Psi more usable.

Anyhow thanks for bringing this up @herrozerro

**Comment by DerDiemen** [comment]
This has been added to the latest update
