### ISSUE TITLE
Scroll bar for Rep scores

### ISSUE THREAD

**Issue by xyleth** [DerDiemen/eclipsephase#33]
On the PC character sheet, the Ego and the Muse tabs have scroll bars but the ID/Rep scores don't.  This means on laptops with limited screen estate you can't see all of your rep scores. 

Can a scroll bar be added to the ID tab please?

**Comment by DerDiemen** [comment]
Heya @xyleth ,
I had a look into this and it will be part of the next update most likely coming tomorrow during the day (I have a playtest for some features today and will draft a new release afterwards.)

**Comment by DerDiemen** [comment]
This has been added to the latest update.
