### ISSUE TITLE
Dialog transparency impact (badly) the readability

### ISSUE THREAD

**Issue by Cafarchon** [DerDiemen/eclipsephase#34]
Hi,

First things first I love what you did for EP! Amazing work! I've just updated to FVTT v10 so I can enjoy your latest version and it is a major upgrade compare to the one I used before. Kudos!

Still I face an issue that I think is related to your module and not FVTT (since I don't have the problem in other modules but feel free to correct me if I am wrong). The dialogs are transparents and look nice but, depending on the conditions, difficult to read. I've attached a screenshot to illustrate the issue but readability could be much worse depending of the background and the various layers displayed.

If this is related to your module would it be possible to have less transparency or a parameter to set the dialog's opacity? It would solve my (and my players) issue!.

Thanks

![EP - Transparency](https://user-images.githubusercontent.com/63412479/204757023-c8005386-d785-4819-b91c-450c91b5bc4f.jpg)

**Comment by DerDiemen** [comment]
Hey there @Cafarchon ,

Did you update to the latest version? All transparancy ha been updated. Also there now is a blur to all dialogs.

All the best

Diemen

**Comment by Cafarchon** [comment]
Damned, updated yesterday! I look into it. May be I didn't update since I am using Foundry through The Forge. Might have a little issue here. I look into it and will post here the result. Thanks for the (amazingly) quick answer.

And I am happy that you saw the version number on the screenshot, was done on purpose :-)

**Comment by Cafarchon** [comment]
Ok that the issue, on the forge the latest available version is 0.7.5. Not sure if I can update that by myself or if I have to wait for it to be updated there...

<img width="2347" alt="Forge - EP" src="https://user-images.githubusercontent.com/63412479/204769254-a23f9fad-cb37-4321-a8b3-0fc401e4fd7d.png">

**Comment by DerDiemen** [comment]
I have to admit, that I don't know how and when "The Forge" updates their modules. But it's already available on foundryvtt itself:

https://foundryvtt.com/packages/eclipsephase

apart from this: If you're able to install a module from a specific manifest file, you can just use this one to get the latest:

https://github.com/DerDiemen/eclipsephase2e-foundryVTT/raw/v0.7.8/system.json

All the best

Diemen

**Comment by Cafarchon** [comment]
Thanks. I asked the question for the update on their Discord. I guess they have a scheduled update process. May be there is a short delay on their part. I will let you know. I'm not worried though, they managed to get up to v0.7.5 they should keep the updates coming ;-).

**Comment by DerDiemen** [comment]
Great! Let me know their answer so I have one in case this happens again some time!

**Comment by Cafarchon** [comment]
A precise answer is coming from help I got on discord. It seems to be related to the (latest) manifest url to the package that is not properly set. Not very sure of the formulation but I linked this ticket so you should have a more precise comment soon from people in the know ;).

**Comment by rikmarais** [comment]
> Great! Let me know their answer so I have one in case this happens again some time!

Heya! I filed an issue for that topic. Hope it helps!

**Comment by Cafarchon** [comment]
Hi !

Version has been updated on The Forge so I am now in 0.7.8 and as you mentioned the issue is fixed. I imagine that you did a few things (or The Forge fixed a few things on their own?) but you can close this one.

Once again thanks a lot, readability is really good now with the blur!
