### ISSUE TITLE
Latest releases 0.7.7 and 0.7.8 system.json is missing id field

### ISSUE THREAD

**Issue by rikmarais** [DerDiemen/eclipsephase#35]
Hi there 👋 

It was [recently pointed out](https://github.com/DerDiemen/eclipsephase/issues/34#issuecomment-1331956105) that the Forge's Bazaar isn't showing the latest versions for this system.

I wanted to let you know that the reason for this is because the repo's `latest` release URL doesn't have a manifest file included, so the Bazaar can't automatically pick up when a new update has been released and grab the latest `.zip`.

It should be an easy fix, if you follow the League of Foundry Developers' [template](https://github.com/League-of-Foundry-Developers/FoundryVTT-Module-Template) that comes with CI/CD. That way you won't have to worry about it again and your players who use the Forge's Bazaar can always get the latest version of the module!

**Comment by DerDiemen** [comment]
So is this a new way of releasing and I will no longer need to include the manifest path in the system.json? Just asking, since I never used this method before (not entirely sure how to do so, but maybe it becomes more clear once I‘m sitting in front of my desktop)

**Comment by rikmarais** [comment]
> So is this a new way of releasing and I will no longer need to include the manifest path in the system.json? Just asking, since I never used this method before (not entirely sure how to do so, but maybe it becomes more clear once I‘m sitting in front of my desktop)

No worries! I'll try to help as best I can!

You don't drop the `manifest` path in the `system.json`.
Instead, `manifest` path in `system.json` points to `https://github.com/DerDiemen/eclipsephase/releases/download/latest/system.json`, and you include the `system.json` in the release assets.
![image](https://user-images.githubusercontent.com/34374883/204789085-11ab1983-f663-4f56-a62c-f8f5b14b705b.png)

You should be able to use [dnd5e](https://github.com/foundryvtt/dnd5e/releases/latest)'s latest release as an reference.

GitHub will always point `/latest` to your latest release, so that [link](https://github.com/DerDiemen/eclipsephase/releases/download/latest/system.json) will always point to the latest release, and each release will still point to its own specific version's `.zip` file just like you have it now.

When the Bazaar checks for updates, it checks your `/latest` manifest link, and if it's been updated, it downloads the new `.zip`. Instant CI/CD!

**Comment by DerDiemen** [comment]
Hey @rikmarais ,

So I tried my luck in finding out how I can make this work, but no one was able to help me with that. Maybe you want to just ping me via Discord (Jorra#7357) as this is a more direct way than this thread here.

All the best

Diemen

**Comment by rikmarais** [comment]
Hey @DerDiemen  

Apologies, I think I've jumped the gun a bit by pointing you at CI/CD with this whole issue. 
CI/CD as detailed [here](https://github.com/League-of-Foundry-Developers/FoundryVTT-Module-Template) is useful, but arcanist from the Foundry and Forge communities pointed out to me that your `0.7.7` and `0.7.8` releases on Foundry's listing should be getting picked up by the Bazaar as well.

On closer inspection, the actual reason why stuff isn't updating automatically on the Bazaar is because the Manifest URL for `0.7.7` and `0.7.8` point to a `system.json` file which is missing the `id` field, so it's being flagged by both the Bazaar and FVTT clients as incompatible.

This causes issues when trying to install `0.7.7` and `0.7.8` of eclipsephase on FVTT `10.290`, but `0.7.5` works fine.
![image](https://user-images.githubusercontent.com/34374883/204878219-d416fd32-1ca4-493b-bfdd-2043ec6d8141.png)
 
arcanist mentioned that they'll get in touch with you, but making a new release which includes `id` in the `system.json` should let everyone get up to the latest version!
I'm going to go ahead and change this issue's name, since I think the real issue has surfaced

All the best to you too!

**Comment by flynnkd** [comment]
setup.js:292 Error: Unable to load valid system manifest data from "https://github.com/DerDiemen/eclipsephase2e-foundryVTT/raw/v0.7.8/system.json"
System Model Validation Errors
[System.id]: may not be a blank string
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1620)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)

**Comment by DerDiemen** [comment]
Hey @flynnkd and @rikmarais ,
this has been adressed after Phi helped me a big deal finding the error. An ID will be distributed with the soon coming v0.7.9, which is currently in playtesting before release.

This ticket will be closed for now. Thank you for the great help!
