### ISSUE TITLE
Character sheet with only consumables shows "no gear" and blocks inventory management

### ISSUE THREAD

**Issue by IcedQuinn** [DerDiemen/eclipsephase#38]
![2023-01-22_17-32 smol](https://user-images.githubusercontent.com/70673392/213970204-db8b94b0-6653-49e1-8cda-b5881a2938ae.jpg)

**Comment by DerDiemen** [comment]
Uh, good catch @IcedQuinn ! Thank you for reporting this! I‘ll fix this with the upcoming release that I‘m currently finishing. :)

**Comment by DerDiemen** [comment]
Hey @IcedQuinn , me again...

So I tested this behaviour and wasn't able to reproduce it. Everytime I put an consumable to the sheet (even a newly added one) it directly shows. This is also the case if I don't have any other item added to the characters inventory.

![image](https://user-images.githubusercontent.com/9768405/214070814-59ac5a4d-63c5-4854-b938-ac8a89190fea.png)

It would be very nice to understand the steps I need to follow to get to this result.

All the best

**Comment by IcedQuinn** [comment]
Hello hello,
Did you try on the released version or a local development copy? I can re-check in soon.

**Comment by IcedQuinn** [comment]
Version 0.8.0.1 
- Create new actor
- Create new Item (Type = Drug)
- Drag the item on to the sheet
- Sheet will now have the blobcatbleach but still show no inventory

Though it's possible you have already fixed this inadvertently :angel:

**Comment by DerDiemen** [comment]
Hey hey @IcedQuinn !

Thank you so much for coming back to me with this description. It helped me a lot and I believe, that I now fixed this issue within the latest version (0.8.6).

https://github.com/DerDiemen/eclipsephase/releases/tag/v0.8.6

Please open a new ticket if the issue still persists!
