### ISSUE TITLE
Moxie Skills are Labled as Insight Skills.

### ISSUE THREAD

**Issue by herrozerro** [DerDiemen/eclipsephase#39]
![image](https://user-images.githubusercontent.com/2041213/218171516-c567dbd7-810d-4a48-8e39-bc6c403b88bb.png)

Moxie Skills are labeled as Insight.

**Comment by DerDiemen** [comment]
Good catch. This will be updated with the version I hope to deploy this weekend. Fingers crossed.

**Comment by DerDiemen** [comment]
Thank you for raising this! It has been fixed in the latest version! 

Keep them bug reports coming! It really helps a lot :)
