### ISSUE TITLE
Predictive Boost does not effect Initiative

### ISSUE THREAD

**Issue by herrozerro** [DerDiemen/eclipsephase#40]
Adding the predictive Boost slight does not effect the initiative value.

**Comment by DerDiemen** [comment]
That‘s correct. Psi sleights don‘t have active effects yet because of the „the bonus gets doubled if above infection rating 33“ rule. That‘s exactly what keeps me awake currently. As soon as I found a solution this will be deployed this weekend.

**Comment by DerDiemen** [comment]
Short update: I found a solution. Will playtest the changes today and on Monday with my players but I believe it looks good so far. Will publish the changes afterwards.

**Comment by DerDiemen** [comment]
All Psi Chi Sleights that have an auto-push mechanic that changes a character's stats are now fully working and even auto-pushing themselves if the 33 threshold is reached!

https://github.com/DerDiemen/eclipsephase/releases/tag/v0.8.6

Thank you for raising this
