### ISSUE TITLE
How does a player modify their pools when taking a short rest?

### ISSUE THREAD

**Issue by herrozerro** [DerDiemen/eclipsephase#41]
Would it be possible to have a an option to allow players to modify their own pools?  when they want to flip a roll it doesn't seem like there is a way for them to spend?

**Comment by DerDiemen** [comment]
Hey there! 
Sure there is. When a roll was done and a switch is (pool wise) possible, players get a prompt whether they want to use a pool or not. If they close this prompt this counts as „accepting the outcome“

**Comment by herrozerro** [comment]
Maybe I'm missing something.  I just rolled infiltrate selecting no pool for the +20.  It failed 71 over a 70.  But nothing popped up or is able to be clicked to flip.

![image](https://user-images.githubusercontent.com/2041213/218238038-4b643417-a04f-421f-bd42-dbf3353898ac.png)

**Comment by herrozerro** [comment]
Also how do they apply points from a short rest?

**Comment by DerDiemen** [comment]
First things first:

after rolling a check this is what you will see
![image](https://user-images.githubusercontent.com/9768405/218246953-34dec237-fb3c-45f1-8e3e-cd7ba714eafc.png)

(in english, but I'm currently testing the German version)

Now as this is an overlay it might happen, that it gets covered by your sheet. In that case just move/minimize (not close) the sheet and you will find it behind the same.

![image](https://user-images.githubusercontent.com/9768405/218247013-2c94fcf0-773a-426a-a80c-f26fa9ebfc62.png)

Now back to the resting-roll question:

There are two things that can happen here 1: You rolled high enough that the roll value covers all your pools. In that case the result will be autodistributed. If this is not the case... 

![image](https://user-images.githubusercontent.com/9768405/218247084-010eca70-658c-4d46-91bc-cf4291135f51.png)

You get to this screen asking you to distribute pool points to a maximum of the rolled result (3 in my case)

If you overspend you will be told and you cannot close the pool recovery tool, if you did not spend all your pool.

![image](https://user-images.githubusercontent.com/9768405/218247158-4e61bb4d-d757-4d1a-bfaa-198850d2d14f.png)

**Comment by herrozerro** [comment]
Huh... I am not seeing anything like that.  I am running the latest version, 0.8.1.

When I run dice rolling I see this as a console error:

![image](https://user-images.githubusercontent.com/2041213/218272932-5f5a3087-a823-491f-9186-d9a4dc08d50b.png)

is dice3d required?

**Comment by herrozerro** [comment]
looks like after installing dice so nice! it worked.  Could this be removed as a dependency though?

**Comment by DerDiemen** [comment]
Aha! Good catch. I‘ll remove this part :)

**Comment by DerDiemen** [comment]
This issue has been solved with the latest version! https://github.com/DerDiemen/eclipsephase/releases/tag/v0.8.6

Thank you for raising it!
