### ISSUE TITLE
The aptitudes label are displayed above the scores

### ISSUE THREAD

**Issue by Cafarchon** [DerDiemen/eclipsephase#43]
Hi,

In the latest version 8.6.1 the aptitudes scores are covered by the aptitudes labels (but for the shortest ones, see attached screen shot).

Keep up the amazing work, it's a true pleasure to play EP with your system Diemen!

Best regards.

<img width="1712" alt="EP - Screenshot" src="https://user-images.githubusercontent.com/63412479/220055570-a24bf9b8-55ab-4141-b6da-9365a88ffe70.png">

**Comment by DerDiemen** [comment]
Hey @Cafarchon,

I encountered this issue before but believe that this is due to a migration error. Can you tell me whether this goes for:

- All characters in your campaign (I just had one)
- A newly created character in the campaign

best regards

Diemen

**Comment by Cafarchon** [comment]
Hey @DerDiemen ,

All the existing characters have the issue.
A new one has not (it displays the short label and not the full ones, see screenshot).

Can I do anything to fix that myself?

Hope this helps.

<img width="1715" alt="EP - New character" src="https://user-images.githubusercontent.com/63412479/220060534-ee794c8f-9b50-4a3d-bbdf-b339de55d782.png">

**Comment by DerDiemen** [comment]
Do you have any pre-migration backup? I could have a look into it, but it may well be that this was an error of a previous version… hrm. 

So here‘s what I would ask of you:
- If you can, provide me a backup file of your world (not the images) before migration
- If not please provide a backup of the world from after it. 

I can then analyze it and put out another migration script. 

Also: If you have a backup you should just be able to put it in and everything should be fine. I know that this bug existet for a short time but it already has been fixed. Sorry that you ran into it though :/

To provide me the files please add Jorra#7357 to your discord.

**Comment by DerDiemen** [comment]
As for a quickfix:

You can use this code and put it into a Macro, save it and then run the macro once to fix this for your campaign. 

`for (let a of game.actors){
  let cogLabel = "ep2e.actorSheet.aptitudes.cognition"
  let cogName = "ep2e.actorSheet.aptitudes.cog"
  let intLabel = "ep2e.actorSheet.aptitudes.intuition"
  let intName = "ep2e.actorSheet.aptitudes.int"
  let refLabel = "ep2e.actorSheet.aptitudes.reflexes"
  let refName = "ep2e.actorSheet.aptitudes.ref"
  let savLabel = "ep2e.actorSheet.aptitudes.savvy"
  let savName = "ep2e.actorSheet.aptitudes.sav"
  let somLabel = "ep2e.actorSheet.aptitudes.somatics"
  let somName = "ep2e.actorSheet.aptitudes.som"
  let wilLabel = "ep2e.actorSheet.aptitudes.willpower"
  let wilName = "ep2e.actorSheet.aptitudes.wil"

  a.update({"system.aptitudes.cog.label":cogLabel, "system.aptitudes.cog.name":cogName, "system.aptitudes.int.label":intLabel, "system.aptitudes.int.name":intName, "system.aptitudes.ref.label":refLabel, "system.aptitudes.ref.name":refName, "system.aptitudes.sav.label":savLabel, "system.aptitudes.sav.name":savName, "system.aptitudes.som.label":somLabel, "system.aptitudes.som.name":somName, "system.aptitudes.wil.label":wilLabel, "system.aptitudes.wil.name":wilName})
}`

It still would be much appreciated if you would provide me with an old backup of your world.

All the best

Diemen

**Comment by Cafarchon** [comment]
I was looking into it but I don't have an old backup sorry :(
I made a backup of the current version and I can provide it if it can helps.
I am trying the macro solution on a cloned world. I let you know if it works as expexcted.

**Comment by Cafarchon** [comment]
I close the issue as it is no longer an issue for me and the provided script should do the trick for users having the same issue. All good here. Thanks again.
