### ISSUE TITLE
Latest update seems to break some characters.

### ISSUE THREAD

**Issue by herrozerro** [DerDiemen/eclipsephase#44]
After updating a few of my player's characters do not open.  I am not sure what is causing it.  I have two PSI characters, but this one does not open.  

Error:

![image](https://user-images.githubusercontent.com/2041213/220117570-6a4e613d-35b7-4299-9065-a2004f42ad42.png)

Character Export:

https://gist.github.com/herrozerro/4f6c4326544de9d0774054e5b9dae7be

**Comment by herrozerro** [comment]
I have a character who is breaking on vehicles and ware as well.  any specific ones that might break this?

**Comment by DerDiemen** [comment]
Now none. It was a bug in the general migration from 0.8.1 to 0.8.6 and was triggered by all new items that have been added after the migration. 

So it can happen with all psi, armor, vehicle, gear, cc & ranged weapons and grenades. I'm trying to find a solution, but it still might take me a while.

**Comment by DerDiemen** [comment]
Okay so if you're using this code in a macro, save and fire it, it should show you all broken characters & items to the console:

let brokenCounter = 0
for (let a of game.actors){
    console.log("Actor name: ", a.name);
    for (let i of a.items){
        if (i.type === "aspect" || i.type === "gear" || i.type === "ccWeapon" || i.type === "rangedWeapon" || i.type === "grenade" || i.type === "vehicle" || i.type === "armor"){
             if (i.system.slotType === ""){
                console.log("The item '", i.name, "' is broken. It's type is '", i.type,"' and it's slotType is '", i.system.slotType,"'");
                brokenCounter++
            }   
        }
    }
    if (brokenCounter === 0){
        console.log("This actor has no broken items");
    }
    else {
        console.log ("This actor has a total of ", brokenCounter, " broken items");
        brokenCounter = 0
    }
}

If you can use this to identify a pattern I can try to write a custom migration code, releasing a hotfix.

All the best

Diemen

**Comment by herrozerro** [comment]
I just restored from backup and it worked.  thanks!

**Comment by DerDiemen** [comment]
You‘re welcome. I might investigate on this further though, if there are more people having the same issue (hopefully not). 

Have a great time playing!
