### ISSUE TITLE
System is unableto be installed on v11.  

### ISSUE THREAD

**Issue by herrozerro** [DerDiemen/eclipsephase#47]
Error received:

![image](https://github.com/DerDiemen/eclipsephase/assets/2041213/24eb5094-f340-4b76-83b5-c4bb9c1aeab2)

New install, trued downloading the system.

**Comment by DerDiemen** [comment]
Heya! I've already fixed this and am currently testing the version, but it looks stable. Will push an update tomorrow or the day after most likely.

**Comment by DerDiemen** [comment]
The system has been updated to v0.9.1 and now successfully supports v11 of Foundry VTT. Please open a new ticket if the issue persists :)
