### ISSUE TITLE
NPC/Threat inventories become inaccessible after creating Know/Exotic skills

### ISSUE THREAD

**Issue by skcb64** [DerDiemen/eclipsephase#48]
After creating any custom skill (for Know, Field, etc skills) on an NPC or Threat sheet, the character's Inventory tab blanks out and becomes totally inaccessible. This also seems to apply to Vehicles and Psi tabs, though I haven't done as much testing on that. This also seems to break the compendium bot sheets as soon as they're imported. Deleting the custom skills on the character sheet seems to reverse the issue (though the vehicle tab is still inaccessible, it seems?)
Occurs on V11, with or without any modules.

**Comment by DerDiemen** [comment]
Hey there!
I already have a profound idea what this can be, though it might take a few days till I have a chance to correct this due to my current workload. 

I‘ll try to fix this till next weekend.

**Comment by DerDiemen** [comment]
This has been fixed in the newly release v0.9.2 - Please report if you're still having trouble with this.

Issue closed
