### ISSUE TITLE
Muse rolls aren't rolling :-)

### ISSUE THREAD

**Issue by Cafarchon** [DerDiemen/eclipsephase#49]
Hi Diemen,

Hope your doing well!

I have an issue with the latest version (0.9.2) on Foundry 11#302) when running on Chrome (Mac OS 13.4.1, Chrome 114.0.5735.133 (latest)), dices are not rolled when I click on a muse's stat or skill.

To me the expected behavior would be to roll the dices when we click on the dice that is displayed next to a muse stat or skill. Behavior should be in line with the one implemented for the character's stat / skills / ...

Hope this helps! And lot of energy for the 1.0 release! 

P.S. Oh, looking at the latest commits (8ab478e) I can see a comment on "Fixed an Issue that prevented muses from rolling dice" so you are aware of the issue already :-). Still, on 0.9.2 it doesn't do the trick for me!

**Comment by DerDiemen** [comment]
Hey there @Cafarchon ,

Yeah, we notices that in our last round as well! I've already implemented a fix, and will release it somewhere this week. I'm currently just working on some updates on ranged weapons and ammunition, to migrate existing character sheets to working with our upcoming tracking system :)

All the best

Diemen

**Comment by DerDiemen** [comment]
This issue has be tackled and solved with v0.9.3! Please open a new ticket if you find this or another bug in the system again.

**Comment by Cafarchon** [comment]
All good for me! Thanks!
