### ISSUE TITLE
Mesh Services Broken

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#50]
Anything added from mesh services does not appear in the inventory. After duplicating the compendium and individually opening and closing each item this is fixed.

https://github.com/DerDiemen/eclipsephase/assets/40039652/30f78921-0cff-4165-a50a-98d6210dda5d

**Comment by DerDiemen** [comment]
Now this is a curious one! I‘ll sit down today and hope to push an update on this tonight/tomorrow! Thank you for reporting :)

**Comment by DerDiemen** [comment]
This issue has be tackled and solved with v0.9.3! Please open a new ticket if you find this or another bug in the system again.
