### ISSUE TITLE
Sex and Gender Fields

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#51]
Currently the sex and gender fields are drop-downs however this unnecessarily limits the choices available. Using text fields instead would be a better option.

**Comment by DerDiemen** [comment]
That‘s a good point, actually! 
Though my thinking behind this was also to already show a spectrum. Do you think that a „custom“ or „other“ selection providing you with given text field would do the trick?

**Comment by DerDiemen** [comment]
Yep! I believe this does the trick... 

![image](https://github.com/DerDiemen/eclipsephase/assets/9768405/aee43433-505f-4535-ba15-d29d5c633819)
![image](https://github.com/DerDiemen/eclipsephase/assets/9768405/4edc5202-2878-4c41-8231-4d5abc3cef54)
![image](https://github.com/DerDiemen/eclipsephase/assets/9768405/4c2f1954-8d22-4df2-820d-a78b15fe7c3e)
![image](https://github.com/DerDiemen/eclipsephase/assets/9768405/46692fa3-de1f-46ee-801d-e069db349123)

Will be implemented with the next update

**Comment by DerDiemen** [comment]
This has been fixed in the latest release (0.9.5) 

Thank you for reporting this issue and keep them coming! :)
