### ISSUE TITLE
No ignore modifiers button

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#55]
You can use pools to ignore all modifiers on a test before rolling. There should be a button like the +20 one before rolling.

**Comment by DerDiemen** [comment]
Yeah, that‘s true. Currently you can spend the pool (by clicking on the pool as a player) but it doesn‘t do anything. I will definitely habe to tackle this before release 1.0

thank you for reporting!

**Comment by DerDiemen** [comment]
This has been added and will be part of the next release!
