### ISSUE TITLE
Can't use flex to add +20 to rolls

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#56]
Flex should be able to be used to add +20 to rolls of any skill similar to mitigating, upgrading and swapping dice.

**Comment by DerDiemen** [comment]
Good catch! I definitely overlooked this. Will add it to one of the upcoming releases (might come rather soon, but I‘m currently struggling with the „how“)

thank you for reporting!

**Comment by DerDiemen** [comment]
This has been fixed and will be part of the upcoming release 0.9.8.5
