### ISSUE TITLE
Keeps Asking for Migration

### ISSUE THREAD

**Issue by itteerde** [DerDiemen/eclipsephase#58]
Keeps asking for Migration after seemingly (no feedback otherwise, including clean console) successful migration was performed.

+ system version: 0.9.8
+ game version: 11.313
+ active modules: none

If cancelling/closing

![image](https://github.com/DerDiemen/eclipsephase/assets/8367477/f4f6cec6-8c4e-4757-85f4-e1942facd822)

as this is my first issue reported for this system, thanks for providing a system (hopefully will start playing it in a few months)

**Comment by DerDiemen** [comment]
Hey there,
thank you for reporting this issue! Can you take a screenshot from the system version from inside the system settings? There is an input field with the last migration in it that should show something.

**Comment by DerDiemen** [comment]
Okay, never mind, I found the issue:
The current migration script is broken in a way, that if you're installing the system anew it will ask you several times to migrate as it migrates only one step at a time. Meaning, that your system migrates even though it doesn't need to and also doing so step by step only after refreshing the page.

I'll address this issue in the next release, but would ask you for now just to refresh the page, migrate, refresh it again, migrate again etc. until you will no longer get this message fired up.

Thanks again for bringing this up!

**Comment by itteerde** [comment]
confirmed workaround, ✅

**Comment by DerDiemen** [comment]
This issues' fix will be part of the next release
