### ISSUE TITLE
Expose Morph Speed as two integer variables

### ISSUE THREAD

**Issue by VacantFanatic** [DerDiemen/eclipsephase#62]
If I'm reading thing correctly morph speed is currently stored as a string "4/20".

Would it be possible to split that and store it as two integers?  

So
"morph.movement.speed"

would be replaced with
morph.movement.base = 4
morph.movement.full = 20

The reason behind the change is that the current variable isn't usable with modules like "Drag Ruler", "Monks token bar" and "Combat Carousel" that give GMs an "at a glance way of tracking movement.

(If I've misread things my apologies and could you point me towards a list of character variables? Thanks!)

**Comment by DerDiemen** [comment]
You're totally correct, this is currently the case!

It's a legacy-issue from when I started all of this (as most of the things around morphs are tbh). I'm planning to update this actually with the morph update after my 1.0 release, but this might be some time in the future, as it requires me to basically refactor the whole morph system. 

I might be in favour of just writing a short script in one of the upcoming patches before Christmas, but I cannot yet promise that it will happen then.

Thank you so so much for reporting this, as I wasn't even aware of tools that are able to define which values to use for movement speed! 

For now I'll put this issue on hold, but depending on my success during the current bug fixes it might be implemented rather quick.

**Comment by DerDiemen** [comment]
This has been implemented and will be part of the upcoming release! Thanks for bringing this up!
