### ISSUE TITLE
Add more info to not enough time to heal card

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#65]
It would be nice if the not enough time to heal card gave the minimum healing time-frame for the morph and the attempted time-frame so it was clearer what was wrong

**Comment by DerDiemen** [comment]
This is a very good point. I think about how to achieve this!

**Comment by DerDiemen** [comment]
This has been implemented and will be part of the upcoming release! Thanks for bringing this up!
![Screenshot 2023-12-20 at 00 53 06](https://github.com/DerDiemen/eclipsephase/assets/9768405/5859f256-7f50-47c8-84d8-795cf8b952bb)
