### ISSUE TITLE
Add units and wound rate to additions

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#66]
Add units and wound rate to additions tab of healing
Ex: Fixers (+1d10/hour | +1/day) or something similar

**Comment by DerDiemen** [comment]
Fair point! Will add this!

**Comment by DerDiemen** [comment]
This has been implemented and will be part of the upcoming release! Thanks for bringing this up!

![Screenshot 2023-12-19 at 13 07 54](https://github.com/DerDiemen/eclipsephase/assets/9768405/01806a97-98c9-4062-a189-89fb91bec550)
