### ISSUE TITLE
Movement variables return null

### ISSUE THREAD

**Issue by VacantFanatic** [DerDiemen/eclipsephase#67]
It looks like the variables being exposed to foundry are the 
morph.movement1.base = null 
and not the bodies.morph1.movement1.base = 4 as intended. (See attached screenshots)

It looks as though the null values should be storing the values for the current morph (morph.movement1.base = currentmorph.movement.base)

![image](https://github.com/DerDiemen/eclipsephase/assets/5420476/35ae41a2-394c-483d-abac-88f14a2031c4)

![image](https://github.com/DerDiemen/eclipsephase/assets/5420476/77ce933c-918e-4c5d-8035-95e5c4611d82)

**Comment by DerDiemen** [comment]
Well... the reason for this rather ... creative... approach was a fix by someone who helped somewhere along the road, to reduce duplicated code, I believe, creating more duplicated code it seems.

Nonetheless I'll try and find a quick fix with v1.0 and will then fix this properly while reworking morphs at whole. Keep you posted on this.

**Comment by VacantFanatic** [comment]
No rush! I know how it can be refactoring and untangling code. Also just as a small note it does seem like the first set of morph variables (the null ones) are  the ones exposed to Foundry.  Trying to reference System.bodies.morph1.movement1 doesn't seem to resolve to anything.

**Comment by DerDiemen** [comment]
So I had a look into drag ruler earlier today and I believe they’re seaking for a format as foundry uses it for e.g. health bars

movement1{
“min”: value,
“max”: value
}

That kind of stuff, since they’re only letting you provide one path. This conflicts with the fact that I’m also storing my movement type there I suppose… - Will try to find a quickfix tomorrow. Let’s see if I find one.

If you have any further information about the format drag ruler wants to be presented with, let me know. Might help a ton.

**Comment by VacantFanatic** [comment]
It should be fine as is? A better snippet to look at is a "speed provider". (Some systems bake these in).

There you could define the base and full movements. The bigger hurdle would be selecting the movement mode as ep can define more than one (e.g. walking/bounding) with their own base and full values. 

https://github.com/Maelstrom-Development/wng-dragruler/blob/master/modules/wng-dragruler.js

In the case that no provider is defined there's a setting where you can select the generic one and use a stat to define the base move and multiply that by an int value for dash (most RPGs would define this as 2x base).

![image](https://github.com/DerDiemen/eclipsephase/assets/5420476/ad698ab4-241d-485b-abae-10787a4aae52)

Monk's token bar does something similar.
![image](https://github.com/DerDiemen/eclipsephase/assets/5420476/d19fef34-3908-45e7-8346-27ff9dec1336)

Hope that helps!

**Comment by DerDiemen** [comment]
Okay, I had a look into it and I have  good and a not-so-good news:

1. providing dragruler with just the base speed works and I can implement a workaround for now that does just that, without any hassle at all...

![Screenshot 2023-12-20 at 23 56 23](https://github.com/DerDiemen/eclipsephase/assets/9768405/001ee85a-1950-4897-9044-2dd66c57652f)

2. unfortunately the EP movement structure is not natively implemented into drag ruler, meaning that you can only use it for morphs which full movement it exact 4 times the base speed. This goes for most of the morphs but not if they have prehensile feet e.g. (or if they're flying)

So I can expose the movement base, but you'll still have limited use for it, as I'm at this point in time, will not write a module for drag ruler to specify this furhter. If you like to do so go ahead. I'm very happy to provide you with the values needed in the main system then :)

**Comment by DerDiemen** [comment]
Just a short note around your post: Had a look into it and it looks fairly simple. I might as well bake this into the system when I'm redesigning morphs next year... so not all hope is lost.

My offer for now would be as follows: I'll provide a general base speed you can multiply with your standard int for now (most likely 5 as this reflects the standard morph) and will revisit this topic once I'm starting my work on morph next year.

Sounds fair?

**Comment by VacantFanatic** [comment]
Oh yeah for sure! (I work in software for a living so I have no delusions about the complexity).  Properly implementing EPs movement (which is already pretty complicated on paper) is a sizeable undertaking.  

Agreed, doing anything other than exposing the base movement of the active Morph would best be left for a release where you're already going to refactor the Morph code.  To fully implement (if at all) is going to require some planning about the how the data is structured.

**Comment by VacantFanatic** [comment]
Did some thinking about this and a possible implementation (in the future) would be:
- Define all movement types for all morphs (walking, flying, bounding etc.) instead of the current movement 1, 2 etc.
- init those to 0/0 (walking.base = 0 walking full = 0) another possibility would be to have pre defined values like slow, medium, fast, etc as defined at the beginning of p 231?
- The player would then select the modes the morph has and populate those values. (player sets walking.base = 4 walking.full = 20) or maybe a toggle with pre-defined values.
- If the player is using a movement type other than walking they could select a corresponding "condition/staus" for their token. (condition = flying)
- The speed provider could then use conditional logic to update and return the base/full values for the toggled "condition" eg Flying. (flying.base / flying.full are returned) 
- If none are set it would default to walking.
- Unreachable would be redefined as "Rushing"

As mentioned above this is likely best left for a full rewrite. Cheers!

**Comment by DerDiemen** [comment]
This looks really useful! Thank you for the work/input :) 

I'll wait the night to see if any game breaking bugs appear and will then push the last update for this year (as I'm travelling over Christmas) 

After this you'll find the exposed base movement with 'actor.system.additionalSystems.movementBase' - and this will most likely not change till the rewrite for morphs is started next somewhere along the line next year.

Have a great time! We'll surely write then from time to time!

**Comment by DerDiemen** [comment]
This has been added and will be part of the next release. Thank you for reporting!

**Comment by VacantFanatic** [comment]
One final update: managed to cobble together a (very basic) speed provider with the base value you exposed.
https://github.com/VacantFanatic/ep-dragruler/releases/tag/alpha_v0.1

**Comment by DerDiemen** [comment]
Thank you so so much for your work <3 ! I’ll have a look into it once I’m back at home in 2024 :)

**Comment by VacantFanatic** [comment]
BTW you can "bake" that directly into the system by:
- adding it as a module in the system.json
- putting the js/mjs file in your module directory
- changing the last line to registerSystem

For an example you can check here 
https://github.com/VacantFanatic/SLAfoundry

Cheers!
